#pragma once
#define WM_SOCKET WM_USER+1
#define MAX_SIZE 4096

///Logic Sever///
#define BUF_SIZE 1024
#define WM_SOCKET WM_USER+1
#define ROOM_MAX_PLAYER 4
#define MAX_MONSTER 10
#define MAX_OBJECT 10
#define SECTOR_LENGTH 10
#define SECTOR_WIDETH 10
#define MAP_MAX_LENGTH 4000
#define MAP_MAX_WIDETH 4000
#define DIVIDE_SECTOR_X 400
#define DIVIDE_SECTOR_Z 400


enum
{
	//ServerType
	SC_MOVE_POSITION = 1,
	SC_MOVE_ERROR_CHECK,
	SC_SECTOR,
	SC_MONSTER_MOVE,
	SC_LOGIN_SUCCESS,
	SC_LOGIN_FAIL,
	SC_READY,
	SC_ROOM_LIST,
	SC_PLAYER_LIST,
	SC_SECTOR_UPDATE,
	SC_REMOVE_PLAYER,
	SC_PUT_PLAYER,
	SC_POSSIBLE_ATTACK,
	SC_STATE_UPDATE,
	SC_MONSTER_UPDATE,
	SC_MONSTER_STATE_UPDATE,
	SC_MONSTER_POS,
	SC_MONSTER_RESET,
	//ClientType
	CS_MOVE = 100,
	CS_STOP,
	CS_USE_SKILL_Q,
	CS_USE_SKILL_W,
	CS_USE_SKILL_E,
	CS_USE_ITEM_S,
	CS_USE_ITEM_D,
	CS_LOGIN_REQUEST,
	CS_CREATE_ROOM,
	CS_INPUT_READY,
	CS_INPUT_START,
	CS_INVITE_SHOP,
	CS_REGISTER_PORTION,
	CS_HEAL_PORTION,
	CS_MANA_PORTION,
	CS_SPEED_PORTION,
	CS_ATTACK_PORTION,
	CS_SELECT_WARRIOR,
	CS_SELECT_WIZARD,
	CS_SELECT_HEALER,
	CS_SELECT_ARCHER,
	CS_KEY_UP,
	CS_KEY_DOWN,
	CS_INFO_REQUSET
};
